import Country from '#models/country'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    const countries = [
      {
        id: 1,
        name: 'Afghanistan',
        capital: 'Kabul',
        phoneCode: '93',
        iso: 'AF',
        emoji: '🇦🇫',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'AFN',
        currencySymbol: '؋',
      },
      {
        id: 2,
        name: 'Aland Islands',
        capital: 'Mariehamn',
        phoneCode: '358',
        iso: 'AX',
        emoji: '🇦🇽',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 3,
        name: 'Albania',
        capital: 'Tirana',
        phoneCode: '355',
        iso: 'AL',
        emoji: '🇦🇱',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'ALL',
        currencySymbol: 'Lek',
      },
      {
        id: 4,
        name: 'Algeria',
        capital: 'Algiers',
        phoneCode: '213',
        iso: 'DZ',
        emoji: '🇩🇿',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'DZD',
        currencySymbol: 'دج',
      },
      {
        id: 5,
        name: 'American Samoa',
        capital: 'Pago Pago',
        phoneCode: '1',
        iso: 'AS',
        emoji: '🇦🇸',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 6,
        name: 'Andorra',
        capital: 'Andorra la Vella',
        phoneCode: '376',
        iso: 'AD',
        emoji: '🇦🇩',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 7,
        name: 'Angola',
        capital: 'Luanda',
        phoneCode: '244',
        iso: 'AO',
        emoji: '🇦🇴',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'AOA',
        currencySymbol: 'Kz',
      },
      {
        id: 8,
        name: 'Anguilla',
        capital: 'The Valley',
        phoneCode: '1',
        iso: 'AI',
        emoji: '🇦🇮',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 9,
        name: 'Antarctica',
        capital: '',
        phoneCode: '672',
        iso: 'AQ',
        emoji: '🇦🇶',
        region: 'Polar',
        subregion: '',
        currency: 'AAD',
        currencySymbol: '$',
      },
      {
        id: 10,
        name: 'Antigua and Barbuda',
        capital: "St. John's",
        phoneCode: '1',
        iso: 'AG',
        emoji: '🇦🇬',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 11,
        name: 'Argentina',
        capital: 'Buenos Aires',
        phoneCode: '54',
        iso: 'AR',
        emoji: '🇦🇷',
        region: 'Americas',
        subregion: 'South America',
        currency: 'ARS',
        currencySymbol: '$',
      },
      {
        id: 12,
        name: 'Armenia',
        capital: 'Yerevan',
        phoneCode: '374',
        iso: 'AM',
        emoji: '🇦🇲',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'AMD',
        currencySymbol: '֏',
      },
      {
        id: 13,
        name: 'Aruba',
        capital: 'Oranjestad',
        phoneCode: '297',
        iso: 'AW',
        emoji: '🇦🇼',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'AWG',
        currencySymbol: 'ƒ',
      },
      {
        id: 14,
        name: 'Australia',
        capital: 'Canberra',
        phoneCode: '61',
        iso: 'AU',
        emoji: '🇦🇺',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 15,
        name: 'Austria',
        capital: 'Vienna',
        phoneCode: '43',
        iso: 'AT',
        emoji: '🇦🇹',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 16,
        name: 'Azerbaijan',
        capital: 'Baku',
        phoneCode: '994',
        iso: 'AZ',
        emoji: '🇦🇿',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'AZN',
        currencySymbol: 'm',
      },
      {
        id: 18,
        name: 'Bahrain',
        capital: 'Manama',
        phoneCode: '973',
        iso: 'BH',
        emoji: '🇧🇭',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'BHD',
        currencySymbol: '.د.ب',
      },
      {
        id: 19,
        name: 'Bangladesh',
        capital: 'Dhaka',
        phoneCode: '880',
        iso: 'BD',
        emoji: '🇧🇩',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'BDT',
        currencySymbol: '৳',
      },
      {
        id: 20,
        name: 'Barbados',
        capital: 'Bridgetown',
        phoneCode: '1',
        iso: 'BB',
        emoji: '🇧🇧',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'BBD',
        currencySymbol: 'Bds$',
      },
      {
        id: 21,
        name: 'Belarus',
        capital: 'Minsk',
        phoneCode: '375',
        iso: 'BY',
        emoji: '🇧🇾',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'BYN',
        currencySymbol: 'Br',
      },
      {
        id: 22,
        name: 'Belgium',
        capital: 'Brussels',
        phoneCode: '32',
        iso: 'BE',
        emoji: '🇧🇪',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 23,
        name: 'Belize',
        capital: 'Belmopan',
        phoneCode: '501',
        iso: 'BZ',
        emoji: '🇧🇿',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'BZD',
        currencySymbol: '$',
      },
      {
        id: 24,
        name: 'Benin',
        capital: 'Porto-Novo',
        phoneCode: '229',
        iso: 'BJ',
        emoji: '🇧🇯',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 25,
        name: 'Bermuda',
        capital: 'Hamilton',
        phoneCode: '1',
        iso: 'BM',
        emoji: '🇧🇲',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'BMD',
        currencySymbol: '$',
      },
      {
        id: 26,
        name: 'Bhutan',
        capital: 'Thimphu',
        phoneCode: '975',
        iso: 'BT',
        emoji: '🇧🇹',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'BTN',
        currencySymbol: 'Nu.',
      },
      {
        id: 27,
        name: 'Bolivia',
        capital: 'Sucre',
        phoneCode: '591',
        iso: 'BO',
        emoji: '🇧🇴',
        region: 'Americas',
        subregion: 'South America',
        currency: 'BOB',
        currencySymbol: 'Bs.',
      },
      {
        id: 155,
        name: 'Bonaire, Sint Eustatius and Saba',
        capital: 'Kralendijk',
        phoneCode: '599',
        iso: 'BQ',
        emoji: '🇧🇶',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 28,
        name: 'Bosnia and Herzegovina',
        capital: 'Sarajevo',
        phoneCode: '387',
        iso: 'BA',
        emoji: '🇧🇦',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'BAM',
        currencySymbol: 'KM',
      },
      {
        id: 29,
        name: 'Botswana',
        capital: 'Gaborone',
        phoneCode: '267',
        iso: 'BW',
        emoji: '🇧🇼',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'BWP',
        currencySymbol: 'P',
      },
      {
        id: 30,
        name: 'Bouvet Island',
        capital: '',
        phoneCode: '0055',
        iso: 'BV',
        emoji: '🇧🇻',
        region: '',
        subregion: '',
        currency: 'NOK',
        currencySymbol: 'ko',
      },
      {
        id: 31,
        name: 'Brazil',
        capital: 'Brasilia',
        phoneCode: '55',
        iso: 'BR',
        emoji: '🇧🇷',
        region: 'Americas',
        subregion: 'South America',
        currency: 'BRL',
        currencySymbol: 'R$',
      },
      {
        id: 32,
        name: 'British Indian Ocean Territory',
        capital: 'Diego Garcia',
        phoneCode: '246',
        iso: 'IO',
        emoji: '🇮🇴',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 33,
        name: 'Brunei',
        capital: 'Bandar Seri Begawan',
        phoneCode: '673',
        iso: 'BN',
        emoji: '🇧🇳',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'BND',
        currencySymbol: 'B$',
      },
      {
        id: 34,
        name: 'Bulgaria',
        capital: 'Sofia',
        phoneCode: '359',
        iso: 'BG',
        emoji: '🇧🇬',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'BGN',
        currencySymbol: 'Лв.',
      },
      {
        id: 35,
        name: 'Burkina Faso',
        capital: 'Ouagadougou',
        phoneCode: '226',
        iso: 'BF',
        emoji: '🇧🇫',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 36,
        name: 'Burundi',
        capital: 'Bujumbura',
        phoneCode: '257',
        iso: 'BI',
        emoji: '🇧🇮',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'BIF',
        currencySymbol: 'FBu',
      },
      {
        id: 37,
        name: 'Cambodia',
        capital: 'Phnom Penh',
        phoneCode: '855',
        iso: 'KH',
        emoji: '🇰🇭',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'KHR',
        currencySymbol: 'KHR',
      },
      {
        id: 38,
        name: 'Cameroon',
        capital: 'Yaounde',
        phoneCode: '237',
        iso: 'CM',
        emoji: '🇨🇲',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FCFA',
      },
      {
        id: 39,
        name: 'Canada',
        capital: 'Ottawa',
        phoneCode: '1',
        iso: 'CA',
        emoji: '🇨🇦',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'CAD',
        currencySymbol: '$',
      },
      {
        id: 40,
        name: 'Cape Verde',
        capital: 'Praia',
        phoneCode: '238',
        iso: 'CV',
        emoji: '🇨🇻',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'CVE',
        currencySymbol: '$',
      },
      {
        id: 41,
        name: 'Cayman Islands',
        capital: 'George Town',
        phoneCode: '1',
        iso: 'KY',
        emoji: '🇰🇾',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'KYD',
        currencySymbol: '$',
      },
      {
        id: 42,
        name: 'Central African Republic',
        capital: 'Bangui',
        phoneCode: '236',
        iso: 'CF',
        emoji: '🇨🇫',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FCFA',
      },
      {
        id: 43,
        name: 'Chad',
        capital: "N'Djamena",
        phoneCode: '235',
        iso: 'TD',
        emoji: '🇹🇩',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FCFA',
      },
      {
        id: 44,
        name: 'Chile',
        capital: 'Santiago',
        phoneCode: '56',
        iso: 'CL',
        emoji: '🇨🇱',
        region: 'Americas',
        subregion: 'South America',
        currency: 'CLP',
        currencySymbol: '$',
      },
      {
        id: 45,
        name: 'China',
        capital: 'Beijing',
        phoneCode: '86',
        iso: 'CN',
        emoji: '🇨🇳',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'CNY',
        currencySymbol: '¥',
      },
      {
        id: 46,
        name: 'Christmas Island',
        capital: 'Flying Fish Cove',
        phoneCode: '61',
        iso: 'CX',
        emoji: '🇨🇽',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 47,
        name: 'Cocos (Keeling) Islands',
        capital: 'West Island',
        phoneCode: '61',
        iso: 'CC',
        emoji: '🇨🇨',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 48,
        name: 'Colombia',
        capital: 'Bogotá',
        phoneCode: '57',
        iso: 'CO',
        emoji: '🇨🇴',
        region: 'Americas',
        subregion: 'South America',
        currency: 'COP',
        currencySymbol: '$',
      },
      {
        id: 49,
        name: 'Comoros',
        capital: 'Moroni',
        phoneCode: '269',
        iso: 'KM',
        emoji: '🇰🇲',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'KMF',
        currencySymbol: 'CF',
      },
      {
        id: 50,
        name: 'Congo',
        capital: 'Brazzaville',
        phoneCode: '242',
        iso: 'CG',
        emoji: '🇨🇬',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FC',
      },
      {
        id: 52,
        name: 'Cook Islands',
        capital: 'Avarua',
        phoneCode: '682',
        iso: 'CK',
        emoji: '🇨🇰',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'NZD',
        currencySymbol: '$',
      },
      {
        id: 53,
        name: 'Costa Rica',
        capital: 'San Jose',
        phoneCode: '506',
        iso: 'CR',
        emoji: '🇨🇷',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'CRC',
        currencySymbol: '₡',
      },
      {
        id: 54,
        name: "Cote D'Ivoire (Ivory Coast)",
        capital: 'Yamoussoukro',
        phoneCode: '225',
        iso: 'CI',
        emoji: '🇨🇮',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 55,
        name: 'Croatia',
        capital: 'Zagreb',
        phoneCode: '385',
        iso: 'HR',
        emoji: '🇭🇷',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 56,
        name: 'Cuba',
        capital: 'Havana',
        phoneCode: '53',
        iso: 'CU',
        emoji: '🇨🇺',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'CUP',
        currencySymbol: '$',
      },
      {
        id: 249,
        name: 'Curaçao',
        capital: 'Willemstad',
        phoneCode: '599',
        iso: 'CW',
        emoji: '🇨🇼',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'ANG',
        currencySymbol: 'ƒ',
      },
      {
        id: 57,
        name: 'Cyprus',
        capital: 'Nicosia',
        phoneCode: '357',
        iso: 'CY',
        emoji: '🇨🇾',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 58,
        name: 'Czech Republic',
        capital: 'Prague',
        phoneCode: '420',
        iso: 'CZ',
        emoji: '🇨🇿',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'CZK',
        currencySymbol: 'Kč',
      },
      {
        id: 51,
        name: 'Democratic Republic of the Congo',
        capital: 'Kinshasa',
        phoneCode: '243',
        iso: 'CD',
        emoji: '🇨🇩',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'CDF',
        currencySymbol: 'FC',
      },
      {
        id: 59,
        name: 'Denmark',
        capital: 'Copenhagen',
        phoneCode: '45',
        iso: 'DK',
        emoji: '🇩🇰',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'DKK',
        currencySymbol: 'Kr.',
      },
      {
        id: 60,
        name: 'Djibouti',
        capital: 'Djibouti',
        phoneCode: '253',
        iso: 'DJ',
        emoji: '🇩🇯',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'DJF',
        currencySymbol: 'Fdj',
      },
      {
        id: 61,
        name: 'Dominica',
        capital: 'Roseau',
        phoneCode: '1',
        iso: 'DM',
        emoji: '🇩🇲',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 62,
        name: 'Dominican Republic',
        capital: 'Santo Domingo',
        phoneCode: '1',
        iso: 'DO',
        emoji: '🇩🇴',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'DOP',
        currencySymbol: '$',
      },
      {
        id: 64,
        name: 'Ecuador',
        capital: 'Quito',
        phoneCode: '593',
        iso: 'EC',
        emoji: '🇪🇨',
        region: 'Americas',
        subregion: 'South America',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 65,
        name: 'Egypt',
        capital: 'Cairo',
        phoneCode: '20',
        iso: 'EG',
        emoji: '🇪🇬',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'EGP',
        currencySymbol: 'ج.م',
      },
      {
        id: 66,
        name: 'El Salvador',
        capital: 'San Salvador',
        phoneCode: '503',
        iso: 'SV',
        emoji: '🇸🇻',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 67,
        name: 'Equatorial Guinea',
        capital: 'Malabo',
        phoneCode: '240',
        iso: 'GQ',
        emoji: '🇬🇶',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FCFA',
      },
      {
        id: 68,
        name: 'Eritrea',
        capital: 'Asmara',
        phoneCode: '291',
        iso: 'ER',
        emoji: '🇪🇷',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'ERN',
        currencySymbol: 'Nfk',
      },
      {
        id: 69,
        name: 'Estonia',
        capital: 'Tallinn',
        phoneCode: '372',
        iso: 'EE',
        emoji: '🇪🇪',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 212,
        name: 'Eswatini',
        capital: 'Mbabane',
        phoneCode: '268',
        iso: 'SZ',
        emoji: '🇸🇿',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'SZL',
        currencySymbol: 'E',
      },
      {
        id: 70,
        name: 'Ethiopia',
        capital: 'Addis Ababa',
        phoneCode: '251',
        iso: 'ET',
        emoji: '🇪🇹',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'ETB',
        currencySymbol: 'Nkf',
      },
      {
        id: 71,
        name: 'Falkland Islands',
        capital: 'Stanley',
        phoneCode: '500',
        iso: 'FK',
        emoji: '🇫🇰',
        region: 'Americas',
        subregion: 'South America',
        currency: 'FKP',
        currencySymbol: '£',
      },
      {
        id: 72,
        name: 'Faroe Islands',
        capital: 'Torshavn',
        phoneCode: '298',
        iso: 'FO',
        emoji: '🇫🇴',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'DKK',
        currencySymbol: 'Kr.',
      },
      {
        id: 73,
        name: 'Fiji Islands',
        capital: 'Suva',
        phoneCode: '679',
        iso: 'FJ',
        emoji: '🇫🇯',
        region: 'Oceania',
        subregion: 'Melanesia',
        currency: 'FJD',
        currencySymbol: 'FJ$',
      },
      {
        id: 74,
        name: 'Finland',
        capital: 'Helsinki',
        phoneCode: '358',
        iso: 'FI',
        emoji: '🇫🇮',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 75,
        name: 'France',
        capital: 'Paris',
        phoneCode: '33',
        iso: 'FR',
        emoji: '🇫🇷',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 76,
        name: 'French Guiana',
        capital: 'Cayenne',
        phoneCode: '594',
        iso: 'GF',
        emoji: '🇬🇫',
        region: 'Americas',
        subregion: 'South America',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 77,
        name: 'French Polynesia',
        capital: 'Papeete',
        phoneCode: '689',
        iso: 'PF',
        emoji: '🇵🇫',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'XPF',
        currencySymbol: '₣',
      },
      {
        id: 78,
        name: 'French Southern Territories',
        capital: 'Port-aux-Francais',
        phoneCode: '262',
        iso: 'TF',
        emoji: '🇹🇫',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 79,
        name: 'Gabon',
        capital: 'Libreville',
        phoneCode: '241',
        iso: 'GA',
        emoji: '🇬🇦',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'XAF',
        currencySymbol: 'FCFA',
      },
      {
        id: 81,
        name: 'Georgia',
        capital: 'Tbilisi',
        phoneCode: '995',
        iso: 'GE',
        emoji: '🇬🇪',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'GEL',
        currencySymbol: 'ლ',
      },
      {
        id: 82,
        name: 'Germany',
        capital: 'Berlin',
        phoneCode: '49',
        iso: 'DE',
        emoji: '🇩🇪',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 83,
        name: 'Ghana',
        capital: 'Accra',
        phoneCode: '233',
        iso: 'GH',
        emoji: '🇬🇭',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'GHS',
        currencySymbol: 'GH₵',
      },
      {
        id: 84,
        name: 'Gibraltar',
        capital: 'Gibraltar',
        phoneCode: '350',
        iso: 'GI',
        emoji: '🇬🇮',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'GIP',
        currencySymbol: '£',
      },
      {
        id: 85,
        name: 'Greece',
        capital: 'Athens',
        phoneCode: '30',
        iso: 'GR',
        emoji: '🇬🇷',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 86,
        name: 'Greenland',
        capital: 'Nuuk',
        phoneCode: '299',
        iso: 'GL',
        emoji: '🇬🇱',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'DKK',
        currencySymbol: 'Kr.',
      },
      {
        id: 87,
        name: 'Grenada',
        capital: "St. George's",
        phoneCode: '1',
        iso: 'GD',
        emoji: '🇬🇩',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 88,
        name: 'Guadeloupe',
        capital: 'Basse-Terre',
        phoneCode: '590',
        iso: 'GP',
        emoji: '🇬🇵',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 89,
        name: 'Guam',
        capital: 'Hagatna',
        phoneCode: '1',
        iso: 'GU',
        emoji: '🇬🇺',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 90,
        name: 'Guatemala',
        capital: 'Guatemala City',
        phoneCode: '502',
        iso: 'GT',
        emoji: '🇬🇹',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'GTQ',
        currencySymbol: 'Q',
      },
      {
        id: 91,
        name: 'Guernsey and Alderney',
        capital: 'St Peter Port',
        phoneCode: '44',
        iso: 'GG',
        emoji: '🇬🇬',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'GBP',
        currencySymbol: '£',
      },
      {
        id: 92,
        name: 'Guinea',
        capital: 'Conakry',
        phoneCode: '224',
        iso: 'GN',
        emoji: '🇬🇳',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'GNF',
        currencySymbol: 'FG',
      },
      {
        id: 93,
        name: 'Guinea-Bissau',
        capital: 'Bissau',
        phoneCode: '245',
        iso: 'GW',
        emoji: '🇬🇼',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 94,
        name: 'Guyana',
        capital: 'Georgetown',
        phoneCode: '592',
        iso: 'GY',
        emoji: '🇬🇾',
        region: 'Americas',
        subregion: 'South America',
        currency: 'GYD',
        currencySymbol: '$',
      },
      {
        id: 95,
        name: 'Haiti',
        capital: 'Port-au-Prince',
        phoneCode: '509',
        iso: 'HT',
        emoji: '🇭🇹',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'HTG',
        currencySymbol: 'G',
      },
      {
        id: 96,
        name: 'Heard Island and McDonald Islands',
        capital: '',
        phoneCode: '672',
        iso: 'HM',
        emoji: '🇭🇲',
        region: '',
        subregion: '',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 97,
        name: 'Honduras',
        capital: 'Tegucigalpa',
        phoneCode: '504',
        iso: 'HN',
        emoji: '🇭🇳',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'HNL',
        currencySymbol: 'L',
      },
      {
        id: 98,
        name: 'Hong Kong S.A.R.',
        capital: 'Hong Kong',
        phoneCode: '852',
        iso: 'HK',
        emoji: '🇭🇰',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'HKD',
        currencySymbol: '$',
      },
      {
        id: 99,
        name: 'Hungary',
        capital: 'Budapest',
        phoneCode: '36',
        iso: 'HU',
        emoji: '🇭🇺',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'HUF',
        currencySymbol: 'Ft',
      },
      {
        id: 100,
        name: 'Iceland',
        capital: 'Reykjavik',
        phoneCode: '354',
        iso: 'IS',
        emoji: '🇮🇸',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'ISK',
        currencySymbol: 'ko',
      },
      {
        id: 101,
        name: 'India',
        capital: 'New Delhi',
        phoneCode: '91',
        iso: 'IN',
        emoji: '🇮🇳',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'INR',
        currencySymbol: '₹',
      },
      {
        id: 102,
        name: 'Indonesia',
        capital: 'Jakarta',
        phoneCode: '62',
        iso: 'ID',
        emoji: '🇮🇩',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'IDR',
        currencySymbol: 'Rp',
      },
      {
        id: 103,
        name: 'Iran',
        capital: 'Tehran',
        phoneCode: '98',
        iso: 'IR',
        emoji: '🇮🇷',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'IRR',
        currencySymbol: '﷼',
      },
      {
        id: 104,
        name: 'Iraq',
        capital: 'Baghdad',
        phoneCode: '964',
        iso: 'IQ',
        emoji: '🇮🇶',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'IQD',
        currencySymbol: 'د.ع',
      },
      {
        id: 105,
        name: 'Ireland',
        capital: 'Dublin',
        phoneCode: '353',
        iso: 'IE',
        emoji: '🇮🇪',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 106,
        name: 'Israel',
        capital: 'Jerusalem',
        phoneCode: '972',
        iso: 'IL',
        emoji: '🇮🇱',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'ILS',
        currencySymbol: '₪',
      },
      {
        id: 107,
        name: 'Italy',
        capital: 'Rome',
        phoneCode: '39',
        iso: 'IT',
        emoji: '🇮🇹',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 108,
        name: 'Jamaica',
        capital: 'Kingston',
        phoneCode: '1',
        iso: 'JM',
        emoji: '🇯🇲',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'JMD',
        currencySymbol: 'J$',
      },
      {
        id: 109,
        name: 'Japan',
        capital: 'Tokyo',
        phoneCode: '81',
        iso: 'JP',
        emoji: '🇯🇵',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'JPY',
        currencySymbol: '¥',
      },
      {
        id: 110,
        name: 'Jersey',
        capital: 'Saint Helier',
        phoneCode: '44',
        iso: 'JE',
        emoji: '🇯🇪',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'GBP',
        currencySymbol: '£',
      },
      {
        id: 111,
        name: 'Jordan',
        capital: 'Amman',
        phoneCode: '962',
        iso: 'JO',
        emoji: '🇯🇴',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'JOD',
        currencySymbol: 'ا.د',
      },
      {
        id: 112,
        name: 'Kazakhstan',
        capital: 'Astana',
        phoneCode: '7',
        iso: 'KZ',
        emoji: '🇰🇿',
        region: 'Asia',
        subregion: 'Central Asia',
        currency: 'KZT',
        currencySymbol: 'лв',
      },
      {
        id: 113,
        name: 'Kenya',
        capital: 'Nairobi',
        phoneCode: '254',
        iso: 'KE',
        emoji: '🇰🇪',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'KES',
        currencySymbol: 'KSh',
      },
      {
        id: 114,
        name: 'Kiribati',
        capital: 'Tarawa',
        phoneCode: '686',
        iso: 'KI',
        emoji: '🇰🇮',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 248,
        name: 'Kosovo',
        capital: 'Pristina',
        phoneCode: '383',
        iso: 'XK',
        emoji: '🇽🇰',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 117,
        name: 'Kuwait',
        capital: 'Kuwait City',
        phoneCode: '965',
        iso: 'KW',
        emoji: '🇰🇼',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'KWD',
        currencySymbol: 'ك.د',
      },
      {
        id: 118,
        name: 'Kyrgyzstan',
        capital: 'Bishkek',
        phoneCode: '996',
        iso: 'KG',
        emoji: '🇰🇬',
        region: 'Asia',
        subregion: 'Central Asia',
        currency: 'KGS',
        currencySymbol: 'лв',
      },
      {
        id: 119,
        name: 'Laos',
        capital: 'Vientiane',
        phoneCode: '856',
        iso: 'LA',
        emoji: '🇱🇦',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'LAK',
        currencySymbol: '₭',
      },
      {
        id: 120,
        name: 'Latvia',
        capital: 'Riga',
        phoneCode: '371',
        iso: 'LV',
        emoji: '🇱🇻',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 121,
        name: 'Lebanon',
        capital: 'Beirut',
        phoneCode: '961',
        iso: 'LB',
        emoji: '🇱🇧',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'LBP',
        currencySymbol: '£',
      },
      {
        id: 122,
        name: 'Lesotho',
        capital: 'Maseru',
        phoneCode: '266',
        iso: 'LS',
        emoji: '🇱🇸',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'LSL',
        currencySymbol: 'L',
      },
      {
        id: 123,
        name: 'Liberia',
        capital: 'Monrovia',
        phoneCode: '231',
        iso: 'LR',
        emoji: '🇱🇷',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'LRD',
        currencySymbol: '$',
      },
      {
        id: 124,
        name: 'Libya',
        capital: 'Tripolis',
        phoneCode: '218',
        iso: 'LY',
        emoji: '🇱🇾',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'LYD',
        currencySymbol: 'د.ل',
      },
      {
        id: 125,
        name: 'Liechtenstein',
        capital: 'Vaduz',
        phoneCode: '423',
        iso: 'LI',
        emoji: '🇱🇮',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'CHF',
        currencySymbol: 'CHf',
      },
      {
        id: 126,
        name: 'Lithuania',
        capital: 'Vilnius',
        phoneCode: '370',
        iso: 'LT',
        emoji: '🇱🇹',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 127,
        name: 'Luxembourg',
        capital: 'Luxembourg',
        phoneCode: '352',
        iso: 'LU',
        emoji: '🇱🇺',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 128,
        name: 'Macau S.A.R.',
        capital: 'Macao',
        phoneCode: '853',
        iso: 'MO',
        emoji: '🇲🇴',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'MOP',
        currencySymbol: '$',
      },
      {
        id: 130,
        name: 'Madagascar',
        capital: 'Antananarivo',
        phoneCode: '261',
        iso: 'MG',
        emoji: '🇲🇬',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'MGA',
        currencySymbol: 'Ar',
      },
      {
        id: 131,
        name: 'Malawi',
        capital: 'Lilongwe',
        phoneCode: '265',
        iso: 'MW',
        emoji: '🇲🇼',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'MWK',
        currencySymbol: 'MK',
      },
      {
        id: 132,
        name: 'Malaysia',
        capital: 'Kuala Lumpur',
        phoneCode: '60',
        iso: 'MY',
        emoji: '🇲🇾',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'MYR',
        currencySymbol: 'RM',
      },
      {
        id: 133,
        name: 'Maldives',
        capital: 'Male',
        phoneCode: '960',
        iso: 'MV',
        emoji: '🇲🇻',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'MVR',
        currencySymbol: 'Rf',
      },
      {
        id: 134,
        name: 'Mali',
        capital: 'Bamako',
        phoneCode: '223',
        iso: 'ML',
        emoji: '🇲🇱',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 135,
        name: 'Malta',
        capital: 'Valletta',
        phoneCode: '356',
        iso: 'MT',
        emoji: '🇲🇹',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 136,
        name: 'Man (Isle of)',
        capital: 'Douglas, Isle of Man',
        phoneCode: '44',
        iso: 'IM',
        emoji: '🇮🇲',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'GBP',
        currencySymbol: '£',
      },
      {
        id: 137,
        name: 'Marshall Islands',
        capital: 'Majuro',
        phoneCode: '692',
        iso: 'MH',
        emoji: '🇲🇭',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 138,
        name: 'Martinique',
        capital: 'Fort-de-France',
        phoneCode: '596',
        iso: 'MQ',
        emoji: '🇲🇶',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 139,
        name: 'Mauritania',
        capital: 'Nouakchott',
        phoneCode: '222',
        iso: 'MR',
        emoji: '🇲🇷',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'MRO',
        currencySymbol: 'MRU',
      },
      {
        id: 140,
        name: 'Mauritius',
        capital: 'Port Louis',
        phoneCode: '230',
        iso: 'MU',
        emoji: '🇲🇺',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'MUR',
        currencySymbol: '₨',
      },
      {
        id: 141,
        name: 'Mayotte',
        capital: 'Mamoudzou',
        phoneCode: '262',
        iso: 'YT',
        emoji: '🇾🇹',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 142,
        name: 'Mexico',
        capital: 'Ciudad de México',
        phoneCode: '52',
        iso: 'MX',
        emoji: '🇲🇽',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'MXN',
        currencySymbol: '$',
      },
      {
        id: 143,
        name: 'Micronesia',
        capital: 'Palikir',
        phoneCode: '691',
        iso: 'FM',
        emoji: '🇫🇲',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 144,
        name: 'Moldova',
        capital: 'Chisinau',
        phoneCode: '373',
        iso: 'MD',
        emoji: '🇲🇩',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'MDL',
        currencySymbol: 'L',
      },
      {
        id: 145,
        name: 'Monaco',
        capital: 'Monaco',
        phoneCode: '377',
        iso: 'MC',
        emoji: '🇲🇨',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 146,
        name: 'Mongolia',
        capital: 'Ulan Bator',
        phoneCode: '976',
        iso: 'MN',
        emoji: '🇲🇳',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'MNT',
        currencySymbol: '₮',
      },
      {
        id: 147,
        name: 'Montenegro',
        capital: 'Podgorica',
        phoneCode: '382',
        iso: 'ME',
        emoji: '🇲🇪',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 148,
        name: 'Montserrat',
        capital: 'Plymouth',
        phoneCode: '1',
        iso: 'MS',
        emoji: '🇲🇸',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 149,
        name: 'Morocco',
        capital: 'Rabat',
        phoneCode: '212',
        iso: 'MA',
        emoji: '🇲🇦',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'MAD',
        currencySymbol: 'DH',
      },
      {
        id: 150,
        name: 'Mozambique',
        capital: 'Maputo',
        phoneCode: '258',
        iso: 'MZ',
        emoji: '🇲🇿',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'MZN',
        currencySymbol: 'MT',
      },
      {
        id: 151,
        name: 'Myanmar',
        capital: 'Nay Pyi Taw',
        phoneCode: '95',
        iso: 'MM',
        emoji: '🇲🇲',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'MMK',
        currencySymbol: 'K',
      },
      {
        id: 152,
        name: 'Namibia',
        capital: 'Windhoek',
        phoneCode: '264',
        iso: 'NA',
        emoji: '🇳🇦',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'NAD',
        currencySymbol: '$',
      },
      {
        id: 153,
        name: 'Nauru',
        capital: 'Yaren',
        phoneCode: '674',
        iso: 'NR',
        emoji: '🇳🇷',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 154,
        name: 'Nepal',
        capital: 'Kathmandu',
        phoneCode: '977',
        iso: 'NP',
        emoji: '🇳🇵',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'NPR',
        currencySymbol: '₨',
      },
      {
        id: 156,
        name: 'Netherlands',
        capital: 'Amsterdam',
        phoneCode: '31',
        iso: 'NL',
        emoji: '🇳🇱',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 157,
        name: 'New Caledonia',
        capital: 'Noumea',
        phoneCode: '687',
        iso: 'NC',
        emoji: '🇳🇨',
        region: 'Oceania',
        subregion: 'Melanesia',
        currency: 'XPF',
        currencySymbol: '₣',
      },
      {
        id: 158,
        name: 'New Zealand',
        capital: 'Wellington',
        phoneCode: '64',
        iso: 'NZ',
        emoji: '🇳🇿',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        currency: 'NZD',
        currencySymbol: '$',
      },
      {
        id: 159,
        name: 'Nicaragua',
        capital: 'Managua',
        phoneCode: '505',
        iso: 'NI',
        emoji: '🇳🇮',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'NIO',
        currencySymbol: 'C$',
      },
      {
        id: 160,
        name: 'Niger',
        capital: 'Niamey',
        phoneCode: '227',
        iso: 'NE',
        emoji: '🇳🇪',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 161,
        name: 'Nigeria',
        capital: 'Abuja',
        phoneCode: '234',
        iso: 'NG',
        emoji: '🇳🇬',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'NGN',
        currencySymbol: '₦',
      },
      {
        id: 162,
        name: 'Niue',
        capital: 'Alofi',
        phoneCode: '683',
        iso: 'NU',
        emoji: '🇳🇺',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'NZD',
        currencySymbol: '$',
      },
      {
        id: 163,
        name: 'Norfolk Island',
        capital: 'Kingston',
        phoneCode: '672',
        iso: 'NF',
        emoji: '🇳🇫',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 115,
        name: 'North Korea',
        capital: 'Pyongyang',
        phoneCode: '850',
        iso: 'KP',
        emoji: '🇰🇵',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'KPW',
        currencySymbol: '₩',
      },
      {
        id: 129,
        name: 'North Macedonia',
        capital: 'Skopje',
        phoneCode: '389',
        iso: 'MK',
        emoji: '🇲🇰',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'MKD',
        currencySymbol: 'ден',
      },
      {
        id: 164,
        name: 'Northern Mariana Islands',
        capital: 'Saipan',
        phoneCode: '1',
        iso: 'MP',
        emoji: '🇲🇵',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 165,
        name: 'Norway',
        capital: 'Oslo',
        phoneCode: '47',
        iso: 'NO',
        emoji: '🇳🇴',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'NOK',
        currencySymbol: 'ko',
      },
      {
        id: 166,
        name: 'Oman',
        capital: 'Muscat',
        phoneCode: '968',
        iso: 'OM',
        emoji: '🇴🇲',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'OMR',
        currencySymbol: '.ع.ر',
      },
      {
        id: 167,
        name: 'Pakistan',
        capital: 'Islamabad',
        phoneCode: '92',
        iso: 'PK',
        emoji: '🇵🇰',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'PKR',
        currencySymbol: '₨',
      },
      {
        id: 168,
        name: 'Palau',
        capital: 'Melekeok',
        phoneCode: '680',
        iso: 'PW',
        emoji: '🇵🇼',
        region: 'Oceania',
        subregion: 'Micronesia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 169,
        name: 'Palestinian Territory Occupied',
        capital: 'East Jerusalem',
        phoneCode: '970',
        iso: 'PS',
        emoji: '🇵🇸',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'ILS',
        currencySymbol: '₪',
      },
      {
        id: 170,
        name: 'Panama',
        capital: 'Panama City',
        phoneCode: '507',
        iso: 'PA',
        emoji: '🇵🇦',
        region: 'Americas',
        subregion: 'Central America',
        currency: 'PAB',
        currencySymbol: 'B/.',
      },
      {
        id: 171,
        name: 'Papua New Guinea',
        capital: 'Port Moresby',
        phoneCode: '675',
        iso: 'PG',
        emoji: '🇵🇬',
        region: 'Oceania',
        subregion: 'Melanesia',
        currency: 'PGK',
        currencySymbol: 'K',
      },
      {
        id: 172,
        name: 'Paraguay',
        capital: 'Asuncion',
        phoneCode: '595',
        iso: 'PY',
        emoji: '🇵🇾',
        region: 'Americas',
        subregion: 'South America',
        currency: 'PYG',
        currencySymbol: '₲',
      },
      {
        id: 173,
        name: 'Peru',
        capital: 'Lima',
        phoneCode: '51',
        iso: 'PE',
        emoji: '🇵🇪',
        region: 'Americas',
        subregion: 'South America',
        currency: 'PEN',
        currencySymbol: 'S/.',
      },
      {
        id: 174,
        name: 'Philippines',
        capital: 'Manila',
        phoneCode: '63',
        iso: 'PH',
        emoji: '🇵🇭',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'PHP',
        currencySymbol: '₱',
      },
      {
        id: 175,
        name: 'Pitcairn Island',
        capital: 'Adamstown',
        phoneCode: '870',
        iso: 'PN',
        emoji: '🇵🇳',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'NZD',
        currencySymbol: '$',
      },
      {
        id: 176,
        name: 'Poland',
        capital: 'Warsaw',
        phoneCode: '48',
        iso: 'PL',
        emoji: '🇵🇱',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'PLN',
        currencySymbol: 'zł',
      },
      {
        id: 177,
        name: 'Portugal',
        capital: 'Lisbon',
        phoneCode: '351',
        iso: 'PT',
        emoji: '🇵🇹',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 178,
        name: 'Puerto Rico',
        capital: 'San Juan',
        phoneCode: '1',
        iso: 'PR',
        emoji: '🇵🇷',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 179,
        name: 'Qatar',
        capital: 'Doha',
        phoneCode: '974',
        iso: 'QA',
        emoji: '🇶🇦',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'QAR',
        currencySymbol: 'ق.ر',
      },
      {
        id: 180,
        name: 'Reunion',
        capital: 'Saint-Denis',
        phoneCode: '262',
        iso: 'RE',
        emoji: '🇷🇪',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 181,
        name: 'Romania',
        capital: 'Bucharest',
        phoneCode: '40',
        iso: 'RO',
        emoji: '🇷🇴',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'RON',
        currencySymbol: 'lei',
      },
      {
        id: 182,
        name: 'Russia',
        capital: 'Moscow',
        phoneCode: '7',
        iso: 'RU',
        emoji: '🇷🇺',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'RUB',
        currencySymbol: '₽',
      },
      {
        id: 183,
        name: 'Rwanda',
        capital: 'Kigali',
        phoneCode: '250',
        iso: 'RW',
        emoji: '🇷🇼',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'RWF',
        currencySymbol: 'FRw',
      },
      {
        id: 184,
        name: 'Saint Helena',
        capital: 'Jamestown',
        phoneCode: '290',
        iso: 'SH',
        emoji: '🇸🇭',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'SHP',
        currencySymbol: '£',
      },
      {
        id: 185,
        name: 'Saint Kitts and Nevis',
        capital: 'Basseterre',
        phoneCode: '1',
        iso: 'KN',
        emoji: '🇰🇳',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 186,
        name: 'Saint Lucia',
        capital: 'Castries',
        phoneCode: '1',
        iso: 'LC',
        emoji: '🇱🇨',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 187,
        name: 'Saint Pierre and Miquelon',
        capital: 'Saint-Pierre',
        phoneCode: '508',
        iso: 'PM',
        emoji: '🇵🇲',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 188,
        name: 'Saint Vincent and the Grenadines',
        capital: 'Kingstown',
        phoneCode: '1',
        iso: 'VC',
        emoji: '🇻🇨',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'XCD',
        currencySymbol: '$',
      },
      {
        id: 189,
        name: 'Saint-Barthelemy',
        capital: 'Gustavia',
        phoneCode: '590',
        iso: 'BL',
        emoji: '🇧🇱',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 190,
        name: 'Saint-Martin (French part)',
        capital: 'Marigot',
        phoneCode: '590',
        iso: 'MF',
        emoji: '🇲🇫',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 191,
        name: 'Samoa',
        capital: 'Apia',
        phoneCode: '685',
        iso: 'WS',
        emoji: '🇼🇸',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'WST',
        currencySymbol: 'SAT',
      },
      {
        id: 192,
        name: 'San Marino',
        capital: 'San Marino',
        phoneCode: '378',
        iso: 'SM',
        emoji: '🇸🇲',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 193,
        name: 'Sao Tome and Principe',
        capital: 'Sao Tome',
        phoneCode: '239',
        iso: 'ST',
        emoji: '🇸🇹',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'STD',
        currencySymbol: 'Db',
      },
      {
        id: 194,
        name: 'Saudi Arabia',
        capital: 'Riyadh',
        phoneCode: '966',
        iso: 'SA',
        emoji: '🇸🇦',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'SAR',
        currencySymbol: '﷼',
      },
      {
        id: 195,
        name: 'Senegal',
        capital: 'Dakar',
        phoneCode: '221',
        iso: 'SN',
        emoji: '🇸🇳',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 196,
        name: 'Serbia',
        capital: 'Belgrade',
        phoneCode: '381',
        iso: 'RS',
        emoji: '🇷🇸',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'RSD',
        currencySymbol: 'din',
      },
      {
        id: 197,
        name: 'Seychelles',
        capital: 'Victoria',
        phoneCode: '248',
        iso: 'SC',
        emoji: '🇸🇨',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'SCR',
        currencySymbol: 'SRe',
      },
      {
        id: 198,
        name: 'Sierra Leone',
        capital: 'Freetown',
        phoneCode: '232',
        iso: 'SL',
        emoji: '🇸🇱',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'SLL',
        currencySymbol: 'Le',
      },
      {
        id: 199,
        name: 'Singapore',
        capital: 'Singapur',
        phoneCode: '65',
        iso: 'SG',
        emoji: '🇸🇬',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'SGD',
        currencySymbol: '$',
      },
      {
        id: 250,
        name: 'Sint Maarten (Dutch part)',
        capital: 'Philipsburg',
        phoneCode: '1721',
        iso: 'SX',
        emoji: '🇸🇽',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'ANG',
        currencySymbol: 'ƒ',
      },
      {
        id: 200,
        name: 'Slovakia',
        capital: 'Bratislava',
        phoneCode: '421',
        iso: 'SK',
        emoji: '🇸🇰',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 201,
        name: 'Slovenia',
        capital: 'Ljubljana',
        phoneCode: '386',
        iso: 'SI',
        emoji: '🇸🇮',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 202,
        name: 'Solomon Islands',
        capital: 'Honiara',
        phoneCode: '677',
        iso: 'SB',
        emoji: '🇸🇧',
        region: 'Oceania',
        subregion: 'Melanesia',
        currency: 'SBD',
        currencySymbol: 'Si$',
      },
      {
        id: 203,
        name: 'Somalia',
        capital: 'Mogadishu',
        phoneCode: '252',
        iso: 'SO',
        emoji: '🇸🇴',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'SOS',
        currencySymbol: 'Sh.so.',
      },
      {
        id: 204,
        name: 'South Africa',
        capital: 'Pretoria',
        phoneCode: '27',
        iso: 'ZA',
        emoji: '🇿🇦',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'ZAR',
        currencySymbol: 'R',
      },
      {
        id: 205,
        name: 'South Georgia',
        capital: 'Grytviken',
        phoneCode: '500',
        iso: 'GS',
        emoji: '🇬🇸',
        region: 'Americas',
        subregion: 'South America',
        currency: 'GBP',
        currencySymbol: '£',
      },
      {
        id: 116,
        name: 'South Korea',
        capital: 'Seoul',
        phoneCode: '82',
        iso: 'KR',
        emoji: '🇰🇷',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'KRW',
        currencySymbol: '₩',
      },
      {
        id: 206,
        name: 'South Sudan',
        capital: 'Juba',
        phoneCode: '211',
        iso: 'SS',
        emoji: '🇸🇸',
        region: 'Africa',
        subregion: 'Middle Africa',
        currency: 'SSP',
        currencySymbol: '£',
      },
      {
        id: 207,
        name: 'Spain',
        capital: 'Madrid',
        phoneCode: '34',
        iso: 'ES',
        emoji: '🇪🇸',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 208,
        name: 'Sri Lanka',
        capital: 'Colombo',
        phoneCode: '94',
        iso: 'LK',
        emoji: '🇱🇰',
        region: 'Asia',
        subregion: 'Southern Asia',
        currency: 'LKR',
        currencySymbol: 'Rs',
      },
      {
        id: 209,
        name: 'Sudan',
        capital: 'Khartoum',
        phoneCode: '249',
        iso: 'SD',
        emoji: '🇸🇩',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'SDG',
        currencySymbol: '.س.ج',
      },
      {
        id: 210,
        name: 'Suriname',
        capital: 'Paramaribo',
        phoneCode: '597',
        iso: 'SR',
        emoji: '🇸🇷',
        region: 'Americas',
        subregion: 'South America',
        currency: 'SRD',
        currencySymbol: '$',
      },
      {
        id: 211,
        name: 'Svalbard and Jan Mayen Islands',
        capital: 'Longyearbyen',
        phoneCode: '47',
        iso: 'SJ',
        emoji: '🇸🇯',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'NOK',
        currencySymbol: 'ko',
      },
      {
        id: 213,
        name: 'Sweden',
        capital: 'Stockholm',
        phoneCode: '46',
        iso: 'SE',
        emoji: '🇸🇪',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'SEK',
        currencySymbol: 'ko',
      },
      {
        id: 214,
        name: 'Switzerland',
        capital: 'Bern',
        phoneCode: '41',
        iso: 'CH',
        emoji: '🇨🇭',
        region: 'Europe',
        subregion: 'Western Europe',
        currency: 'CHF',
        currencySymbol: 'CHf',
      },
      {
        id: 215,
        name: 'Syria',
        capital: 'Damascus',
        phoneCode: '963',
        iso: 'SY',
        emoji: '🇸🇾',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'SYP',
        currencySymbol: 'LS',
      },
      {
        id: 216,
        name: 'Taiwan',
        capital: 'Taipei',
        phoneCode: '886',
        iso: 'TW',
        emoji: '🇹🇼',
        region: 'Asia',
        subregion: 'Eastern Asia',
        currency: 'TWD',
        currencySymbol: '$',
      },
      {
        id: 217,
        name: 'Tajikistan',
        capital: 'Dushanbe',
        phoneCode: '992',
        iso: 'TJ',
        emoji: '🇹🇯',
        region: 'Asia',
        subregion: 'Central Asia',
        currency: 'TJS',
        currencySymbol: 'SM',
      },
      {
        id: 218,
        name: 'Tanzania',
        capital: 'Dodoma',
        phoneCode: '255',
        iso: 'TZ',
        emoji: '🇹🇿',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'TZS',
        currencySymbol: 'TSh',
      },
      {
        id: 219,
        name: 'Thailand',
        capital: 'Bangkok',
        phoneCode: '66',
        iso: 'TH',
        emoji: '🇹🇭',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'THB',
        currencySymbol: '฿',
      },
      {
        id: 17,
        name: 'The Bahamas',
        capital: 'Nassau',
        phoneCode: '1',
        iso: 'BS',
        emoji: '🇧🇸',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'BSD',
        currencySymbol: 'B$',
      },
      {
        id: 80,
        name: 'The Gambia ',
        capital: 'Banjul',
        phoneCode: '220',
        iso: 'GM',
        emoji: '🇬🇲',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'GMD',
        currencySymbol: 'D',
      },
      {
        id: 63,
        name: 'Timor-Leste',
        capital: 'Dili',
        phoneCode: '670',
        iso: 'TL',
        emoji: '🇹🇱',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 220,
        name: 'Togo',
        capital: 'Lome',
        phoneCode: '228',
        iso: 'TG',
        emoji: '🇹🇬',
        region: 'Africa',
        subregion: 'Western Africa',
        currency: 'XOF',
        currencySymbol: 'CFA',
      },
      {
        id: 221,
        name: 'Tokelau',
        capital: '',
        phoneCode: '690',
        iso: 'TK',
        emoji: '🇹🇰',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'NZD',
        currencySymbol: '$',
      },
      {
        id: 222,
        name: 'Tonga',
        capital: "Nuku'alofa",
        phoneCode: '676',
        iso: 'TO',
        emoji: '🇹🇴',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'TOP',
        currencySymbol: '$',
      },
      {
        id: 223,
        name: 'Trinidad and Tobago',
        capital: 'Port of Spain',
        phoneCode: '1',
        iso: 'TT',
        emoji: '🇹🇹',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'TTD',
        currencySymbol: '$',
      },
      {
        id: 224,
        name: 'Tunisia',
        capital: 'Tunis',
        phoneCode: '216',
        iso: 'TN',
        emoji: '🇹🇳',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'TND',
        currencySymbol: 'ت.د',
      },
      {
        id: 225,
        name: 'Turkey',
        capital: 'Ankara',
        phoneCode: '90',
        iso: 'TR',
        emoji: '🇹🇷',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'TRY',
        currencySymbol: '₺',
      },
      {
        id: 226,
        name: 'Turkmenistan',
        capital: 'Ashgabat',
        phoneCode: '993',
        iso: 'TM',
        emoji: '🇹🇲',
        region: 'Asia',
        subregion: 'Central Asia',
        currency: 'TMT',
        currencySymbol: 'T',
      },
      {
        id: 227,
        name: 'Turks and Caicos Islands',
        capital: 'Cockburn Town',
        phoneCode: '1',
        iso: 'TC',
        emoji: '🇹🇨',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 228,
        name: 'Tuvalu',
        capital: 'Funafuti',
        phoneCode: '688',
        iso: 'TV',
        emoji: '🇹🇻',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'AUD',
        currencySymbol: '$',
      },
      {
        id: 229,
        name: 'Uganda',
        capital: 'Kampala',
        phoneCode: '256',
        iso: 'UG',
        emoji: '🇺🇬',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'UGX',
        currencySymbol: 'USh',
      },
      {
        id: 230,
        name: 'Ukraine',
        capital: 'Kyiv',
        phoneCode: '380',
        iso: 'UA',
        emoji: '🇺🇦',
        region: 'Europe',
        subregion: 'Eastern Europe',
        currency: 'UAH',
        currencySymbol: '₴',
      },
      {
        id: 231,
        name: 'United Arab Emirates',
        capital: 'Abu Dhabi',
        phoneCode: '971',
        iso: 'AE',
        emoji: '🇦🇪',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'AED',
        currencySymbol: 'إ.د',
      },
      {
        id: 232,
        name: 'United Kingdom',
        capital: 'London',
        phoneCode: '44',
        iso: 'GB',
        emoji: '🇬🇧',
        region: 'Europe',
        subregion: 'Northern Europe',
        currency: 'GBP',
        currencySymbol: '£',
      },
      {
        id: 233,
        name: 'United States',
        capital: 'Washington',
        phoneCode: '1',
        iso: 'US',
        emoji: '🇺🇸',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 234,
        name: 'United States Minor Outlying Islands',
        capital: '',
        phoneCode: '1',
        iso: 'UM',
        emoji: '🇺🇲',
        region: 'Americas',
        subregion: 'Northern America',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 235,
        name: 'Uruguay',
        capital: 'Montevideo',
        phoneCode: '598',
        iso: 'UY',
        emoji: '🇺🇾',
        region: 'Americas',
        subregion: 'South America',
        currency: 'UYU',
        currencySymbol: '$',
      },
      {
        id: 236,
        name: 'Uzbekistan',
        capital: 'Tashkent',
        phoneCode: '998',
        iso: 'UZ',
        emoji: '🇺🇿',
        region: 'Asia',
        subregion: 'Central Asia',
        currency: 'UZS',
        currencySymbol: 'лв',
      },
      {
        id: 237,
        name: 'Vanuatu',
        capital: 'Port Vila',
        phoneCode: '678',
        iso: 'VU',
        emoji: '🇻🇺',
        region: 'Oceania',
        subregion: 'Melanesia',
        currency: 'VUV',
        currencySymbol: 'VT',
      },
      {
        id: 238,
        name: 'Vatican City State (Holy See)',
        capital: 'Vatican City',
        phoneCode: '379',
        iso: 'VA',
        emoji: '🇻🇦',
        region: 'Europe',
        subregion: 'Southern Europe',
        currency: 'EUR',
        currencySymbol: '€',
      },
      {
        id: 239,
        name: 'Venezuela',
        capital: 'Caracas',
        phoneCode: '58',
        iso: 'VE',
        emoji: '🇻🇪',
        region: 'Americas',
        subregion: 'South America',
        currency: 'VES',
        currencySymbol: 'Bs',
      },
      {
        id: 240,
        name: 'Vietnam',
        capital: 'Hanoi',
        phoneCode: '84',
        iso: 'VN',
        emoji: '🇻🇳',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        currency: 'VND',
        currencySymbol: '₫',
      },
      {
        id: 241,
        name: 'Virgin Islands (British)',
        capital: 'Road Town',
        phoneCode: '1',
        iso: 'VG',
        emoji: '🇻🇬',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 242,
        name: 'Virgin Islands (US)',
        capital: 'Charlotte Amalie',
        phoneCode: '1',
        iso: 'VI',
        emoji: '🇻🇮',
        region: 'Americas',
        subregion: 'Caribbean',
        currency: 'USD',
        currencySymbol: '$',
      },
      {
        id: 243,
        name: 'Wallis and Futuna Islands',
        capital: 'Mata Utu',
        phoneCode: '681',
        iso: 'WF',
        emoji: '🇼🇫',
        region: 'Oceania',
        subregion: 'Polynesia',
        currency: 'XPF',
        currencySymbol: '₣',
      },
      {
        id: 244,
        name: 'Western Sahara',
        capital: 'El-Aaiun',
        phoneCode: '212',
        iso: 'EH',
        emoji: '🇪🇭',
        region: 'Africa',
        subregion: 'Northern Africa',
        currency: 'MAD',
        currencySymbol: 'MAD',
      },
      {
        id: 245,
        name: 'Yemen',
        capital: 'Sanaa',
        phoneCode: '967',
        iso: 'YE',
        emoji: '🇾🇪',
        region: 'Asia',
        subregion: 'Western Asia',
        currency: 'YER',
        currencySymbol: '﷼',
      },
      {
        id: 246,
        name: 'Zambia',
        capital: 'Lusaka',
        phoneCode: '260',
        iso: 'ZM',
        emoji: '🇿🇲',
        region: 'Africa',
        subregion: 'Southern Africa',
        currency: 'ZMW',
        currencySymbol: 'ZK',
      },
      {
        id: 247,
        name: 'Zimbabwe',
        capital: 'Harare',
        phoneCode: '263',
        iso: 'ZW',
        emoji: '🇿🇼',
        region: 'Africa',
        subregion: 'Eastern Africa',
        currency: 'ZWL',
        currencySymbol: '$',
      },
    ]

    let num = 0

    for (const country of countries) {
        console.log('country', num++, country.name)
      await Country.updateOrCreate(
        { name: country.name },
        {
          id: country.id,
          name: country.name,
          phoneCode: country.phoneCode,
          capital: country.capital,
          iso: country.iso,
          emoji: country.emoji,
          region: country.region,
          subregion: country.subregion,
          currency: country.currency,
          currencySymbol: country.currency,
        }
      )
    }
  }
}
